@startuml
entity "Products" as Products <<Сущность>> {
    + Id_project : UUID [PK]
    + Name : VARCHAR(225)
    + Description : TEXT
    + Price : DECIMAL(10,2)
    --
    + Category : Object
    + Customs_info : Object
}

entity "Categories" as Categories <<Коллекция>> {
    + category_id : UUID [PK]
    + category_name : VARCHAR(100)
    + category_description : TEXT
    --
    + category_rules : Object
}

entity "CustomsInfos" as CustomsInfo <<Коллекция>> {
    + customs_id : UUID [PK]
    + country : VARCHAR(100)
    + customs_description : TEXT
    + tariff_code : String
}

entity "CategoryRules" as CategoryRules <<Коллекция>> {
    + rule_id : UUID [PK]
    + rule_name : VARCHAR(100)
    + rule_description : TEXT
    + valid_from : DATE
    + valid_to : DATE
}

Products *-- Categories : содержит (встраиваются)
Products *-- CustomsInfo : содержит (встраиваются)
Categories *-- CategoryRules : содержит (встраиваются)

@enduml
